### PR TITLE
Fix kmscon not restarting the login shell

### LINKED ISSUE #80: kmscon enters zombie state
Hello,

I'm running an up-to-date NixOS system.  I have installed kmscon and it successfully starts up, replacing the kernel console and agetty.  The problem appears if I switch to a VT, but don't do anything to log in.  I start in X at tty2, and switch to tty1, where I see kmscon take control of the display and present a login prompt.  I create no input at all.   If I go back to tty2, then after about a minute, I can check on tty1 again and it will display the error, "Login timed out after 60 seconds".  Keyboard input is displayed, but ignored.  I am still able to switch to other ttys.  The process table will show that kmscon instance is now a zombie.  This is 100% predictable on any of the ttys.

This is the relevant part of my configuration.nix:
  services.kmscon = {
    enable = true;
    hwRender = true;
    fonts = [ { name = "Inconsolata Nerd Font"; package = pkgs.inconsolata-nerdfont; } ];
    extraConfig = ''
      font-size=16
      font-dpi=255
      font-engine=pango
      xkb-model=pc105
      xkb-layout=us
      gpus=all
      render-engine=gltex
    '';
  };

  console = {
    font = "Lat2-Terminus16";
    useXkbConfig = true; # use xkb.options in tty.
    earlySetup = true;
  };

### LINKED ISSUE #82: Freeze issue on logout / CTRL+d
Hi, I want to report my current issue using KMSCon.

## Version
Latest Git commit installed via the AUR package `kmscon-patched-git`.

## OS
ArchLinux, latest updates as of today (2024-07-01)

## What should happen
When logging out from a TTY which uses KMSCon, I expect to be asked for credentials again.

## What happens instead
When using either CTRL+d or `logout`, the shell freezes and I am unable to do anything.
The best way I found for resetting it is to jump to another terminal and kill the hang up kmscon process.

## Other information
Not sure what can help, ping me here and I can provide any sort of logs and sort

### PR DESCRIPTION
**Pull request by kdj0c**
Sometime the SIGCHLD handler is not called, but kmscon still receives a HUP on the pty file descriptor. In this case, reap the child, and spawn another login process, to avoid hanging for ever on a defunct child.

Fix #82 
Fix #80

### CODE REVIEW

File: src/pty.c [hunk 1]
```diff
@@ -462,6 +490,7 @@ static int read_buf(struct kmscon_pty *pty)
 		} else if (errno != EWOULDBLOCK) {
 			log_debug("cannot read from pty of child %d (%d): %m",
 				  pty->child, errno);
+			handle_hup(pty);
```
Comment (Aetf) [inline src/pty.c:493]: Could you explain this line here? AFAIK, it seems none of the possible errno from read is HUP related, at least according to the man page https://man.archlinux.org/man/core/man-pages/read.2.en

**Review by Aetf — COMMENTED** [review]
Thanks for the PR!

File: src/pty.c (hunk 1 above)
Comment (kdj0c) [reply src/pty.c:493]: When investigating, the first error I've seen is a -EIO reading the pty pipe, when the child process has exited. I then noticed the mask & EV_HUP check, and move the handle_hup() there.
I decided to keep also a call here, in case for some reason kmscon missed the EV_HUP event, but I don't know if it can happen in practice. Anyway this call is harmless, and will do nothing if the child has not exited.

I can either remove this line, or add a comment.

Comment (kdj0c) [reply src/pty.c:496]: Thanks, I've added a comment, and I fixed indentation in handle_hup() while at it.

**Review by Aetf — APPROVED** [review]

**Comment by Vogtinator** [comment]
> Sometime the SIGCHLD handler is not called

The reason for that is that SIGCHLD is not blocked before pango creates its own glib thread. I made a RFC fix here: https://github.com/Aetf/kmscon/pull/106
